# Generated by Django 3.0.8 on 2020-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studnet',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('sadd', models.CharField(max_length=50)),
                ('scontact', models.IntegerField()),
            ],
        ),
    ]
